import Head from 'next/head';
import { useMemo, useState } from 'react';

import styles from '../styles/Home.module.css';

interface Pokemon {
  id: number;
  name: string;
  image: string;
}

export default function Home({ pokemon }: { pokemon: Pokemon[] }) {
  const [filter, setFilter] = useState('');

  const filteredPokemon = useMemo(
    () =>
      pokemon.filter(p =>
        p.name.toLowerCase().includes(filter.toLocaleLowerCase()),
      ),
    [filter, pokemon],
  );

  return (
    <div className={styles.main}>
      <Head>
        <title>Pokemon App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <input
          type="text"
          value={filter}
          onChange={e => setFilter(e.target.value)}
          className={styles.search}
          data-cy="searchBox"
        />
      </div>
      <div className={styles.container}>
        {filteredPokemon.slice(0, 20).map(p => (
          <div key={p.id} className={styles.image}>
            <img
              alt={p.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
            />
            <h2>{p.name}</h2>
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch(
    'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json',
  );
  return {
    props: {
      pokemon: await response.json(),
    },
  };
}
